# For more explanations, see: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024: false

# MD033/no-inline-html Inline HTML [Element: p]
MD033: false

# MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading
MD041: false
