on:
  pull_request:
    paths:
    - '**.rs'
    - docker-image/**
    - Cargo.toml
  workflow_dispatch:

name: Test Dockerfile

jobs:
  test-docker:
    name: Test Docker image
    runs-on: ubuntu-latest
    needs: publish-crate
    defaults:
      run:
        working-directory: ./docker-image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build container
      run: docker build -t test-container .
    - name: Run container
      run: docker run --name test-container -d -i -t test-container
    - name: Exec ff in container
      run: docker exec -d test-container ff --help
