on:
  pull_request:
    paths:
    - '**.rs'
    - docker-image/**
    - Cargo.toml
  workflow_dispatch:

name: Test Dockerfile

jobs:
  test-docker:
    name: Test Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker-image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build container
      run: docker build -t container .
    - name: Run container and exec
      run: docker run -it --rm --name running-container container ff --help
