on:
  pull_request:
    paths:
    - src/lib/**.rs
    - Cargo.toml
  workflow_dispatch:

name: Binaries testing

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check rustdoc build
      run: cargo test --bin --all-features
